### ISSUE TITLE
Istaknuti sljedece namasko vrijeme

### ISSUE THREAD

**Issue by ahmic** [vaktija/vaktija.ba#2]
Dosta je lakse bilo ranije kada se "na prvu" moglo vidjeti kada je sljedeci namaz. Ako odgovara nesto ovako mogu poslati PR

![](https://i.imgur.com/F9lY7tZ.png)

**Comment by vaktija** [comment]
Hvala za prijedlog, do daljnjeg je ovako. Usput, bilo je vec ideja, moguce da ce biti minor update

![vaktija](https://user-images.githubusercontent.com/1972177/63885508-cc58c780-c9d8-11e9-88e8-a4938a689e52.png)
