### ISSUE TITLE
alarm/notifikacija na web stranici

### ISSUE THREAD

**Issue by ahmedkrdzalic** [vaktija/vaktija.ba#23]
Selam, 
Dobar dio vremena provedem na racunaru, pogotovo u vrijeme podne, ikindije i aksama. Skoro sve vrijeme drzim mobitel okrenut na skrin, da ne bi gubio koncentraciju dok radim, i imam sluske na glavi sto me sprejecava da cujem nekada notifikaciju na mobitelu.

Vjerujem da ima jos dosta ljudi koji se nadju ceto u slicnoj situaciji, pa mislim da ne bi bilo lose ubaciti da te vaktija.ba obavjesti/upali alarm 10 minuta prije isteka namaza.

Ako mogu nekako pomoci, volio bih. (mozda cak da napisem neko rjesenje pa da bacim pull req?)

P.S. Da vas Allah dz.s. nagradi za ovako koristan projekat.

**Comment by vaktija** [comment]
Alejkumusselam,

Hvala za javljanje, amin i Vas. Sto se tice notifikacija, postavljene su na 15min. Mozete sacekati 15min do nekog vakta iskocice notifikacija (na desktop verziji vaktija.ba web stranice). Tek tada, kada se okine notifikacija, moze se dodati permisija za notifikacije na Desktop/Browser/Web verziji aplikacije.

p.s.
import ReactNotifications from "react-browser-notifications";
