### ISSUE TITLE
Namaz "za jednog sata" ne zvuči prirodno.

### ISSUE THREAD

**Issue by demahum** [vaktija/vaktija.ba#3]
<img width="136" alt="Screen Shot 2019-10-10 at 14 34 09" src="https://user-images.githubusercontent.com/8499022/66570174-587c1400-eb6d-11e9-9ec6-aea1ce1e9e7e.png">

Za "jedan" sat bi vjerovatno bila konstrukcija koju bi većina upotrijebila u govoru.

**Comment by vaktija** [comment]
Hvala za javljanje, to je known issue, trenutno se u aplikaciji koristi momentjs (https://momentjs.com/) i bs lokalizacija koja je tako implementirana/prevedena, sad za sad ostaje ovako. Mozda bude nekih intervencija pa da se napravi neki override, prijedlozi su dobrodosli.

https://momentjs.com/docs/#/displaying/to/

https://github.com/moment/moment/blob/develop/locale/bs.js

Nesta slicno ima ovdje:

https://github.com/vaktija/vaktija.ba/blob/master/src/components/Daily.js

moment.updateLocale("bs", {
    iMonths: [
        "Muharrem",
        "Safer",
        "Rebi'u-l-evvel",
        "Rebi'u-l-ahir",
        "Džumade-l-ula",
        "Džumade-l-uhra",
        "Redžeb",
        "Ša'ban",
        "Ramazan",
        "Ševval",
        "Zu-l-ka'de",
        "Zu-l-hidždže"
    ],
    weekdaysShort: ["ned", "pon", "uto", "sri", "čet", "pet", "sub"]
});
